FROM dart:2.18.6-sdk

WORKDIR /taskapi

ADD . /taskapi/

RUN dart pub get

RUN dart pub global activate conduit 4.1.6

EXPOSE 6100

ENTRYPOINT ["sh", "-c", "dart pub run conduit:conduit serve --port 6969"]